on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/jj/raku-zef-gha
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install test deps and prove6
      run: |
        zef install --deps-only --/test .
        which prove6 >/dev/null 2>&1 || zef install --/test App::Prove6
    - name: Run prove6 + behave
      run: ./test.raku
